[workspace]
members = ["workflow-core", "workflow-runtime", "workflow-macros"]
resolver = "2"

[workspace.package]
license = "MIT"

[workspace.dependencies]
tracing = "0.1"
petgraph = "0.8"
bytes = { version = "1" }
chrono = "0.4"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rkyv = { version = "0.8", features = ["std", "bytecheck"] }
bytecheck = "0.8"
tokio = { version = "1", features = ["rt", "macros"] }
